/*
 * MainJFrame.java
 *
 * Created on 25. toukokuuta 2006, 19:07
 */

package com.tictactoe.fun.game1;

import java.awt.BorderLayout;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;

import com.tictactoe.fun.game1.srivathsan.MyPlayer;

/**
 *
 * Quick hackety hack game for 5-in-a-row game. 95% Netbeans Matisse generated code for basic game layout.
 * @author  Antti
 */
public class MainJFrame extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;
    private static final int SIZE = 18;
    ArenaCanvas gameCanvas;
    
    /** Creates new form MainJFrame */
    public MainJFrame(String[] args) {
        initComponents();
        Vector<Player> algorithms = new Vector<Player>();
        
        //----------------------------------------------
        //  Add your algorithms here!
        //---------------------------------------------
        algorithms.addElement(new MyPlayer("Srivaths"));     
        algorithms.addElement(new RandomOpponent("LuckyJack"));  
        


        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(algorithms));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(algorithms));        
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(1);
        
        Player one = (Player) jComboBox1.getSelectedItem();
        one.setSide(Piece.CROSS);
        Player two = (Player)jComboBox2.getSelectedItem();
        two.setSide(Piece.ROUND);        
        this.gameCanvas=new ArenaCanvas(statusLabel, SIZE, one,  two);
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(this.gameCanvas, BorderLayout.CENTER);
        jButton1ActionPerformed(null);
        pack();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jLabel1.setText("X:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("O:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Start new");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });


        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 380, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 355, Short.MAX_VALUE)
        );

        jButton2.setText("Move");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Autoplay 10 games");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        
        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(jButton2)
                        .add(10, 10, 10)
                        .add(jButton3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(statusLabel))
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 138, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jComboBox2, 0, 119, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jButton1)
                    .add(jLabel2)
                    .add(jComboBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jButton2)
                    .add(jButton3)
                    .add(statusLabel))
                .add(16, 16, 16)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         this.gameCanvas.move();
         repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Map<Player,Integer> vals = new HashMap<Player,Integer>();
        vals.put(this.gameCanvas.one, 0);
        vals.put(this.gameCanvas.two, 0);
        
        int rounds=10;
        for(int i=0; i<rounds; i++) {
        //start new game 
        jButton1ActionPerformed(null);
        //play to end
         this.gameCanvas.autoplay();
         if(this.gameCanvas.winner!=null) {
          int score = vals.get(this.gameCanvas.winner);
          vals.put(this.gameCanvas.winner, score+1);
         }
        }
        System.out.println("Scores for "+rounds+" rounds: "+vals);
         repaint();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jPanel1.remove(this.gameCanvas);
        
        Player one = (Player)jComboBox1.getSelectedItem();
        one.setSide(Piece.CROSS);
        Player two = (Player)jComboBox2.getSelectedItem();
        two.setSide(Piece.ROUND);
        if(one==two) {
            statusLabel.setText("Same algorithm instance can't be chosen, add multiple instances to play against yourself");
            
        }else {
          this.gameCanvas=new ArenaCanvas(statusLabel, SIZE, one, two);
          jPanel1.add(this.gameCanvas, BorderLayout.CENTER);
          this.gameCanvas.start();
        }
        pack();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(final String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame(args).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
    
}
